#!/usr/bin/env bash

set -e
set -o pipefail

echo "Installing NPM deps..."
yarn install --frozen-lockfile

echo "<link rel=\"stylesheet\" href=\"https://unpkg.com/tailwindcss@3.2.4/src/css/preflight.css\"><link rel=\"stylesheet\" href=\"https://rsms.me/inter/inter.css?v=3.19\"><div id=root></div><script src="out/main.js"></script>" > index.html

echo "Starting examples build server..."
clojure -A:examples -M -m shadow.cljs.devtools.cli watch examples
