#!/usr/bin/env bash

set -e
set -o pipefail

echo "Installing NPM deps..."
npm ci

echo "<link rel=\"stylesheet\" href=\"/out/main.css\"><div id=root></div><script src=\"/out/main.js\"></script>" > index.html

echo "Starting examples build server..."
npx concurrently "clojure -A:examples -M -m shadow.cljs.devtools.cli watch examples" "npx @tailwindcss/cli -i ./dev/uix/main.css -o ./out/main.css --watch"
